name: Build Windows

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4  # Atualizado para v4
        with:
          submodules: recursive

      - name: Configurar e Compilar
        run: |
          mkdir build
          cd build
          cmake .. -T ClangCL -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DBUILD_SHARED_LIBS=OFF -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON
          cmake --build . --config Release --target ymir_libretro

      - name: Entregar a DLL para Download
        uses: actions/upload-artifact@v4  # ATUALIZADO PARA V4 (Resolve o erro vermelho)
        with:
          name: ymir_libretro_windows
          path: build/**/ymir_libretro.dll
