name: Compilar Ymir Libretro (Windows)

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar o código
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configurar e Compilar
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DBUILD_SHARED_LIBS=ON -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON
        cmake --build . --config Release --target ymir_libretro

    - name: Salvar o Arquivo .dll
      uses: actions/upload-artifact@v4
      with:
        name: ymir_libretro_windows
        path: "**/*ymir_libretro*"
