name: Compilar Ymir Libretro (Windows)

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar o código
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configurar e Compilar
      run: |
        mkdir build
        cd build
        # Removi as flags que causaram o erro de 'assert' e 'constant expression'
        cmake .. -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DBUILD_SHARED_LIBS=OFF
        cmake --build . --config Release

    - name: Salvar o Arquivo .dll
      uses: actions/upload-artifact@v4
      with:
        name: ymir_libretro_windows
        # Usamos o radar para garantir que ele ache a DLL onde quer que ela caia
        path: "**/*.dll"
